extends Node
## Localization (autoload `Loc`). Every visible string lives here under a
## dotted key; UI never hardcodes text. Switching language emits
## `language_changed`, and every screen re-reads its strings live.

signal language_changed

const LANGS := ["no", "en"]

const STRINGS := {
	"no": {
		"game.title": "SPENN",
		"game.titleAccent": "2",
		"game.tagline": "HOLD SNORENE UNNA LINJEN",
		"menu.play": "Dra for å spille",
		"menu.best": "Rekord",
		"menu.settings": "Innstillinger",
		"menu.skip": "TRYKK FOR Å HOPPE OVER",
		"menu.stats": "Statistikk",
		"menu.skins": "Kuler",
		"menu.daily": "Dagens utfordring",
		"menu.dailyBest": "Dagens rekord",
		"menu.missions": "Oppdrag",
		"mission.done": "OPPDRAG FULLFØRT",
		"mission.kills": "Knus %s fiender i én runde",
		"mission.score": "Få %s poeng i én runde",
		"mission.wave": "Nå bølge %s",
		"mission.bank": "Lag %s veggskudd i én runde",
		"mission.overload": "Utløs %s overbelastninger i én runde",
		"mission.chain": "Lag %s kjedereaksjoner i én runde",
		"mission.cut": "Kapp %s snorer i én runde",
		"mission.double": "Lag %s dobbelttreff i én runde",
		"mission.survive": "Overlev %s sekunder",
		"mission.break": "Bryt %s formasjoner i én runde",
		"mission.break.one": "Bryt en formasjon",
		"mission.cut.one": "Kapp en snor",
		"mission.chain.one": "Lag en kjedereaksjon",
		"stats.title": "STATISTIKK",
		"stats.runs": "RUNDER",
		"stats.best": "REKORD",
		"stats.total": "TOTALE POENG",
		"stats.wave": "BESTE BØLGE",
		"stats.kills": "FIENDER KNUST",
		"stats.accuracy": "TREFFSIKKERHET",
		"stats.missions": "OPPDRAG FULLFØRT",
		"stats.time": "SPILLETID (T:MIN)",
		"skins.title": "KULER",
		"skins.total": "TOTALT %s POENG",
		"skins.equipped": "I bruk",
		"skins.locked": "Låses opp ved %s",
		"skin.gold": "GULL",
		"skin.copper": "KOBBER",
		"skin.chrome": "KROM",
		"skin.jade": "JADE",
		"skin.obsidian": "OBSIDIAN",
		"skin.ember": "GLØD",
		"hud.wave": "BØLGE %d",
		"hud.waveWord": "Bølge",
		"hud.left": "%d igjen",
		"hud.finale": "Finale!",
		"pause.score": "Poeng",
		"pause.wave": "Bølge",
		"pause.time": "Tid",
		"settings.sec.sound": "LYD",
		"settings.sec.game": "SPILL",
		"settings.sec.access": "TILGJENGELIGHET",
		"settings.sec.lang": "SPRÅK",
		"wave.clear": "BØLGE %d RENSKET",
		"habit.left": "DE HAR MERKET AT DU SIKTER TIL VENSTRE",
		"habit.right": "DE HAR MERKET AT DU SIKTER TIL HØYRE",
		"habit.rhythm": "DE HAR LÆRT RYTMEN DIN",
		"hazard.gust": "VINDKAST",
		"hazard.gustSub": "VINDEN TAR BÅDE KULER OG FIENDER",
		"hazard.dark": "MØRKLEGGING",
		"hazard.darkSub": "BARE ØYNENE LYSER",
		"hazard.gold": "GULLFIENDE",
		"hazard.goldSub": "TREFF DEN FØR DEN FLYKTER",
		"gold.pop": "GULL +%d",
		"gold.fled": "DEN SLAPP UNNA",
		"evolve.title": "DE VOKSER",
		"evolve.sub": "RINGER SOM FÅR HENGE I FRED, HERDES",
		"evolve.pop": "HERDET!",
		"skill.rescue": "REDDET!",
		"acro.title": "DE SVINGER",
		"acro.sub": "DE SVINGER SEG OVER TIL NABOENS TAU – TREFF DEM I LUFTA",
		"acro.caught": "FANGET!",
		"acro.slip": "UPS! +%d",
		"skill.air": "LUFTSKUDD",
		"skill.swing": "PENDELTREFF",
		"nemesis.back": "%s ER TILBAKE",
		"nemesis.sub": "DEN SOM SLAPP GJENNOM – TA HEVN",
		"nemesis.revenge": "HEVN! +%d",
		"nemesis.0": "ARR-RINGEN",
		"nemesis.1": "JERNKJEVEN",
		"nemesis.2": "TVILLINGEN",
		"nemesis.3": "PINNEN",
		"nemesis.4": "STUPEREN",
		"nemesis.5": "VOKTER-VIDAR",
		"nemesis.7": "SNELLEMANN",
		"nemesis.8": "SKYGGEN",
		"nemesis.9": "DOKTOR DRYPP",
		"nemesis.10": "SPEILGLISET",
		"perk.new": "NY FORDEL",
		"stance.1": "VAKTSOM – REAGERER RASKERE",
		"stance.2": "RASENDE – STUPER OG SYNKER FORT",
		"stance.3": "VETERAN – SMARTERE, ETT LIV TIL",
		"enemy.141": "SPRETT-DYKKER|Gynger opp og ned på strikken. Tim skuddet til den snur.",
		"enemy.142": "TVILLING-DYKKER|Deler seg i to små dråper når du treffer den.",
		"enemy.143": "KJEMPEDRÅPE|Stor og tung: to treff, og den stuper lengre.",
		"enemy.104": "HOPPERING|Hopper sidelengs med jevne mellomrom. Sikt der den lander.",
		"enemy.103": "KJEMPERING|Stor og treg, men tåler to treff.",
		"finale.title": "FINALE",
		"finale.sub": "MESTEREN KOMMER – TA DEN FOR Å VINNE BØLGEN",
		"finale.boss": "FINALE: SPINNEREN",
		"finale.won": "MESTER FELT! +%d",
		"wmood.calm": "ROLIG BØLGE · FÅ, MEN LURE",
		"wmood.chaos": "KAOS · EN SVERM AV SMÅTT",
		"wmood.grumpy": "SUR BØLGE · GRINETE OG STERKE",
		"wmood.cute": "SØT BØLGE · USKYLDIG? NEPPE",
		"mood.rage": "SINNA!",
		"gold.drop": "LYSDRÅPE",
		"mood.help": "HJELP, HJELP!",
		"shove.title": "DYTTING",
		"shove.sub": "SURE FIENDER DYTTER NABOEN OG SMYGER UNNA. SKYT FØR ARMEN SLÅR – ELLER TREFF DEN MENS DEN LADER",
		"shove.name": "DYTT!",
		"shove.nudge": "PUFF!",
		"shove.stopped": "AVBRUTT!",
		"cunning.dead": "DEN SPILTE DØD!",
		"cunning.busted": "AVSLØRT! +50",
		"cunning.empty": "DE SER AT DU ER TOM!",
		"cunning.sneak": "SNIK!",
		"cunning.swap": "DE BYTTER PLASS!",
		"hud.waveLabel": "BØLGE",
		"perk.heavy": "Tunge kuler",
		"perk.heavy.d": "TREFF PÅ PANSREDE FIENDER TELLER DOBBELT",
		"perk.edge": "Skarp egg",
		"perk.edge.d": "ETT TREFF KUTTER TAUET, OG KUTT ER LETTERE",
		"perk.flow": "Lang flyt",
		"perk.flow.d": "+2,5 SEK FLYT, MÅLEREN FYLLES 20 % RASKERE",
		"perk.rack": "Større stativ",
		"perk.rack.d": "EN KULE EKSTRA I STATIVET",
		"perk.reload": "Rask lading",
		"perk.reload.d": "KULENE LADES 15 % RASKERE",
		"perk.sight": "Langt sikte",
		"perk.sight.d": "SIKTELINJEN VISER DOBBELT SÅ LANGT",
		"perk.magnet": "Magnetkule",
		"perk.magnet.d": "KULENE BØYER SEG MOT NÆRMESTE FIENDE",
		"perk.charge": "Superlading",
		"perk.charge.d": "OVERBELASTNING LADES 25 % RASKERE",
		"perk.knot": "Ny knute",
		"perk.knot.d": "FÅ TILBAKE EN TAPT KNUTE",
		"tactic.1": "UNNVIKELSE",
		"tactic.1.sub": "DE HAR LÆRT Å SE SKUDDET KOMME",
		"tactic.2": "FINTER",
		"tactic.2.sub": "FØLG ØYNENE – DE RØPER RETNINGEN",
		"tactic.3": "RYTMEN DIN",
		"tactic.3.sub": "DE LESER TEMPOET DITT – VARIER DET",
		"tactic.4": "SAMARBEID",
		"tactic.4.sub": "DE SPRER SEG OG STUPER SAMMEN",
		"team.plunge": "SAMLET STUP!",
		"flow.title": "FLYT",
		"flow.badge": "FLYT · RASK LADING · +1×",
		"flow.sub": "RASK LADING · +1 MULTIPLIKATOR",
		"boss.stage": "SPINNEREN · TRINN %d",
		"popup.bubble": "BOBLE",
		"popup.mirror": "SPEIL",
		"skill.break": "FORMASJON BRUTT",
		"pause.title": "Pause",
		"pause.resume": "Fortsett",
		"pause.restart": "Start på nytt",
		"pause.settings": "Innstillinger",
		"pause.mainMenu": "Hovedmeny",
		"pause.best": "Rekord  %s",
		"pause.hint": "Dobbelttrykk for pause",
		"gameOver.title": "SPILLET ER OVER",
		"gameOver.score": "POENG",
		"gameOver.bestScore": "BESTE RESULTAT",
		"gameOver.time": "TID",
		"gameOver.accuracy": "TREFF",
		"gameOver.restart": "Prøv igjen",
		"gameOver.mainMenu": "Hovedmeny",
		"record.new": "NY REKORD",
		"record.near": "%s til rekord",
		"record.daily": "DAGENS REKORD",
		"record.prev": "Forrige rekord  %s",
		"gameOver.near": "Så nær!",
		"gameOver.nearSub": "%s poeng unna rekorden",
		"hud.newWave": "Ny beste bølge",
		"stats.new": "Ny!",
		"settings.sec.data": "DATA",
		"settings.reset": "Nullstill statistikk",
		"settings.resetHint": "Hold inne · kulene beholdes",
		"settings.resetDone": "Nullstilt",
		"settings.title": "Innstillinger",
		"settings.music": "Musikk",
		"settings.effects": "Effekter",
		"settings.haptics": "Vibrasjon",
		"settings.reducedMotion": "Reduserte animasjoner",
		"settings.aimGuide": "Siktelinje",
		"settings.tilt": "Vippeeffekt",
		"settings.noSensor": "Ingen sensor",
		"settings.language": "Språk",
		"settings.languageName": "Norsk",
		"settings.back": "Tilbake",
		"settings.credits": "Musikk: «Mesmerizing Galaxy» og «Dreamy Flashback» av Kevin MacLeod (incompetech.com), CC BY 4.0\nLyd og partikler: Kenney.nl, CC0",
		"settings.on": "På",
		"settings.off": "Av",
		"settings.level.0": "Av",
		"settings.level.1": "Lav",
		"settings.level.2": "Middels",
		"settings.level.3": "Høy",
		"event.survive": "OVERLEV",
		"event.surviveSub": "HOLD DEM UNNA LINJEN",
		"event.formation": "FORMASJON",
		"event.formationSub": "FELL LEDEREN MED KRONEN",
		"event.rush": "STORM",
		"event.rushSub": "DYKKERE FRA BJELKEN",
		"event.boss": "SPINNEREN",
		"event.bossSub": "SKYT I SKJOLDGLIPEN",
		"popup.pierce": "GJENNOMSLAG",
		"popup.combo": "KOMBO ×%d",
		"popup.split": "SPLITT",
		"popup.blocked": "SKJOLD",
		"popup.streak": "SERIE %d",
		"popup.triple": "TREDELT SKUDD",
		"popup.lifeLost": "KNUTE RØK",
		"popup.chain": "KJEDE ×%d",
		"skill.bank": "VEGGSKUDD",
		"skill.long": "LANGSKUDD",
		"skill.double": "DOBBELTREFF",
		"skill.triple": "TRIPPELTREFF",
		"skill.multi": "%d-TREFF",
		"skill.cut": "SNORKUTT",
		"skill.clutch": "SISTE SEKUND",
		"skill.chain": "KJEDEREAKSJON",
		"overload.title": "OVERBELASTNING",
		"overload.sub": "ALT GÅR GJENNOM · DOBBEL POENG",
		"overload.hint": "FULL SPENNING GIR OVERBELASTNING",
		"gameOver.gap": "%s POENG FRA REKORDEN",
		"gameOver.close": "SÅ NÆRE",
		"gameOver.overloads": "OVERBELASTNING",
		"popup.extraKnot": "+1 KNUTE",
		"enemy.new": "NY FIENDE",
		"enemy.0": "VAKT|Søker dekning bak andre når du sikter. Slipp før den flytter seg.",
		"enemy.1": "TUNGVEKT|To treff. Blir rasende og stuper etter det første.",
		"enemy.2": "SPLITTER|Deler seg i to dykkere.",
		"enemy.3": "PENDEL|Svinger alltid. Tim vendepunktet.",
		"enemy.4": "DYKKER|Skjelver, så stuper den. Skyt mens den skjelver.",
		"enemy.5": "VOKTER|Skjoldet vender mot deg. Bank via veggen eller kapp snoren.",
		"enemy.6": "SPINNEREN|Skyt i glipen mellom skjoldene.",
		"enemy.7": "SNELLE|Vinsjer seg opp når du sikter. Vær rask, eller bank via veggen.",
		"enemy.8": "SKYGGE|Blir usynlig i perioder. Skudd går gjennom den da.",
		"enemy.9": "LEGEN|Lapper de andre, eller gir dem en boble som tar ett skudd. Ta den først.",
		"enemy.10": "SPEILET|Kaster rene skudd rett tilbake. Treff med en kule som har sprettet.",
		"enemy.11": "PIPP|En liten hermegås: kopierer triksene til de store og fanger merkene som kastes.",
		"enemy.12": "PAKKIS|Deler ut triks-merker fra sekken sin. Ta den før triksene sprer seg.",
		"nemesis.11": "PIPPEN",
		"nemesis.12": "PAKKIS-PELLE",
		"charm.title": "TRIKS-MERKER",
		"charm.sub": "DE DELER TRIKS – SKYT PERLA UNDER FIENDEN FOR Å KNUSE DET",
		"charm.1": "BOBLE: TÅLER ETT SKUDD",
		"charm.2": "SPRETT: LYNRASK UNNVIKELSE",
		"charm.3": "SKYGGE: BLIR USYNLIG",
		"charm.4": "BALLONG: SVEVER OPP",
		"charm.5": "LIANE: SVINGER UNNA",
		"charm.broken": "TRIKS KNUST +%d",
		"charm.pass": "DE DELER TRIKS!",
		"charm.swap": "DE BYTTER TRIKS!",
		"charm.copy": "HERMEGÅS!",
	},
	"en": {
		"game.title": "TAUT",
		"game.titleAccent": "1",
		"game.tagline": "KEEP THE STRINGS OFF THE LINE",
		"menu.play": "Pull to play",
		"menu.best": "Best",
		"menu.settings": "Settings",
		"menu.skip": "TAP TO SKIP",
		"menu.stats": "Stats",
		"menu.skins": "Balls",
		"menu.daily": "Daily challenge",
		"menu.dailyBest": "Today's best",
		"menu.missions": "Missions",
		"mission.done": "MISSION COMPLETE",
		"mission.kills": "Break %s enemies in one run",
		"mission.score": "Score %s in one run",
		"mission.wave": "Reach wave %s",
		"mission.bank": "Make %s bank shots in one run",
		"mission.overload": "Trigger %s overloads in one run",
		"mission.chain": "Set off %s chain reactions in one run",
		"mission.cut": "Cut %s strings in one run",
		"mission.double": "Make %s double kills in one run",
		"mission.survive": "Survive %s seconds",
		"mission.break": "Break %s formations in one run",
		"mission.break.one": "Break a formation",
		"mission.cut.one": "Cut a string",
		"mission.chain.one": "Set off a chain reaction",
		"stats.title": "STATS",
		"stats.runs": "RUNS",
		"stats.best": "BEST",
		"stats.total": "TOTAL POINTS",
		"stats.wave": "BEST WAVE",
		"stats.kills": "ENEMIES BROKEN",
		"stats.accuracy": "ACCURACY",
		"stats.missions": "MISSIONS DONE",
		"stats.time": "PLAY TIME (H:MIN)",
		"skins.title": "BALLS",
		"skins.total": "%s POINTS IN TOTAL",
		"skins.equipped": "Equipped",
		"skins.locked": "Unlocks at %s",
		"skin.gold": "GOLD",
		"skin.copper": "COPPER",
		"skin.chrome": "CHROME",
		"skin.jade": "JADE",
		"skin.obsidian": "OBSIDIAN",
		"skin.ember": "EMBER",
		"hud.wave": "WAVE %d",
		"hud.waveWord": "Wave",
		"hud.left": "%d to go",
		"hud.finale": "Finale!",
		"pause.score": "Score",
		"pause.wave": "Wave",
		"pause.time": "Time",
		"settings.sec.sound": "SOUND",
		"settings.sec.game": "GAME",
		"settings.sec.access": "ACCESSIBILITY",
		"settings.sec.lang": "LANGUAGE",
		"wave.clear": "WAVE %d CLEARED",
		"habit.left": "THEY'VE NOTICED YOU FAVOUR THE LEFT",
		"habit.right": "THEY'VE NOTICED YOU FAVOUR THE RIGHT",
		"habit.rhythm": "THEY'VE LEARNED YOUR RHYTHM",
		"hazard.gust": "GUST",
		"hazard.gustSub": "THE WIND TAKES BALLS AND ENEMIES ALIKE",
		"hazard.dark": "BLACKOUT",
		"hazard.darkSub": "ONLY THE EYES GLOW",
		"hazard.gold": "GOLDEN ONE",
		"hazard.goldSub": "HIT IT BEFORE IT FLEES",
		"gold.pop": "GOLD +%d",
		"gold.fled": "IT GOT AWAY",
		"evolve.title": "THEY GROW",
		"evolve.sub": "RINGS LEFT ALONE HARDEN",
		"evolve.pop": "HARDENED!",
		"skill.rescue": "SAVED!",
		"acro.title": "THEY SWING",
		"acro.sub": "THEY SWING OVER TO A NEIGHBOUR'S ROPE – HIT THEM MID-AIR",
		"acro.caught": "CAUGHT!",
		"acro.slip": "OOPS! +%d",
		"skill.air": "AIR SHOT",
		"skill.swing": "PENDULUM",
		"nemesis.back": "%s IS BACK",
		"nemesis.sub": "THE ONE THAT GOT THROUGH – TAKE REVENGE",
		"nemesis.revenge": "REVENGE! +%d",
		"nemesis.0": "SCAR RING",
		"nemesis.1": "IRON JAW",
		"nemesis.2": "THE TWIN",
		"nemesis.3": "THE STICK",
		"nemesis.4": "THE DIVER",
		"nemesis.5": "GUARD GUS",
		"nemesis.7": "REEL RAY",
		"nemesis.8": "THE SHADE",
		"nemesis.9": "DOCTOR DRIP",
		"nemesis.10": "MIRROR GRIN",
		"perk.new": "NEW PERK",
		"stance.1": "WARY – QUICKER TO DODGE",
		"stance.2": "FURIOUS – LUNGES AND SINKS FAST",
		"stance.3": "VETERAN – SMARTER, ONE MORE LIFE",
		"enemy.141": "BOBBING DIVER|Bobs up and down on its bungee. Time the turn.",
		"enemy.142": "TWIN DIVER|Splits into two little drops when you hit it.",
		"enemy.143": "BIG DROP|Big and heavy: two hits, and it dives further.",
		"enemy.104": "HOP RING|Hops sideways every few seconds. Aim where it lands.",
		"enemy.103": "BIG RING|Big and slow, but takes two hits.",
		"finale.title": "FINALE",
		"finale.sub": "THE CHAMPION COMES – TAKE IT TO WIN THE WAVE",
		"finale.boss": "FINALE: THE SPINNER",
		"finale.won": "CHAMPION DOWN! +%d",
		"wmood.calm": "CALM WAVE · FEW, BUT CUNNING",
		"wmood.chaos": "CHAOS · A SWARM OF LITTLE ONES",
		"wmood.grumpy": "GRUMPY WAVE · CROSS AND TOUGH",
		"wmood.cute": "CUTE WAVE · INNOCENT? HARDLY",
		"mood.rage": "FURIOUS!",
		"gold.drop": "LIGHT DROP",
		"mood.help": "HELP, HELP!",
		"shove.title": "SHOVING",
		"shove.sub": "GRUMPY ONES SHOVE A NEIGHBOUR AND SLIP AWAY. SHOOT BEFORE THE ARM STRIKES – OR HIT IT WHILE IT WINDS UP",
		"shove.name": "SHOVE!",
		"shove.nudge": "NUDGE!",
		"shove.stopped": "STOPPED!",
		"cunning.dead": "IT PLAYED DEAD!",
		"cunning.busted": "BUSTED! +50",
		"cunning.empty": "THEY SEE YOU'RE EMPTY!",
		"cunning.sneak": "SNEAKY!",
		"cunning.swap": "THEY SWAPPED!",
		"hud.waveLabel": "WAVE",
		"perk.heavy": "Heavy balls",
		"perk.heavy.d": "HITS ON ARMOURED ENEMIES COUNT DOUBLE",
		"perk.edge": "Keen edge",
		"perk.edge.d": "ONE STRIKE CUTS A ROPE, AND CUTS COME EASIER",
		"perk.flow": "Long flow",
		"perk.flow.d": "+2.5 S OF FLOW, THE METER FILLS 20% FASTER",
		"perk.rack": "Bigger rack",
		"perk.rack.d": "ONE MORE BALL IN THE RACK",
		"perk.reload": "Quick reload",
		"perk.reload.d": "BALLS RELOAD 15% FASTER",
		"perk.sight": "Long sight",
		"perk.sight.d": "THE AIM GUIDE REACHES TWICE AS FAR",
		"perk.magnet": "Magnet ball",
		"perk.magnet.d": "BALLS CURVE TOWARD THE NEAREST ENEMY",
		"perk.charge": "Supercharge",
		"perk.charge.d": "OVERLOAD CHARGES 25% FASTER",
		"perk.knot": "New knot",
		"perk.knot.d": "GET A LOST KNOT BACK",
		"tactic.1": "DODGING",
		"tactic.1.sub": "THEY'VE LEARNED TO SEE YOUR SHOT COMING",
		"tactic.2": "FEINTS",
		"tactic.2.sub": "WATCH THE EYES – THEY GIVE IT AWAY",
		"tactic.3": "YOUR RHYTHM",
		"tactic.3.sub": "THEY READ YOUR TIMING – MIX IT UP",
		"tactic.4": "TEAMWORK",
		"tactic.4.sub": "THEY SCATTER AND PLUNGE TOGETHER",
		"team.plunge": "ALL TOGETHER!",
		"flow.title": "FLOW",
		"flow.badge": "FLOW · FAST RELOAD · +1×",
		"flow.sub": "FAST RELOAD · +1 MULTIPLIER",
		"boss.stage": "THE SPINNER · STAGE %d",
		"popup.bubble": "BUBBLE",
		"popup.mirror": "MIRROR",
		"skill.break": "FORMATION BROKEN",
		"pause.title": "Paused",
		"pause.resume": "Resume",
		"pause.restart": "Restart",
		"pause.settings": "Settings",
		"pause.mainMenu": "Main menu",
		"pause.best": "Best  %s",
		"pause.hint": "Double-tap to pause",
		"gameOver.title": "GAME OVER",
		"gameOver.score": "SCORE",
		"gameOver.bestScore": "BEST SCORE",
		"gameOver.time": "TIME",
		"gameOver.accuracy": "ACCURACY",
		"gameOver.restart": "Try again",
		"gameOver.mainMenu": "Main menu",
		"record.new": "NEW RECORD",
		"record.near": "%s to beat your best",
		"record.daily": "TODAY'S BEST",
		"record.prev": "Previous best  %s",
		"gameOver.near": "So close!",
		"gameOver.nearSub": "%s points short of your best",
		"hud.newWave": "New best wave",
		"stats.new": "New!",
		"settings.sec.data": "DATA",
		"settings.reset": "Reset statistics",
		"settings.resetHint": "Hold to confirm · balls are kept",
		"settings.resetDone": "Reset done",
		"settings.title": "Settings",
		"settings.music": "Music",
		"settings.effects": "Effects",
		"settings.haptics": "Vibration",
		"settings.reducedMotion": "Reduced motion",
		"settings.aimGuide": "Aim guide",
		"settings.tilt": "Tilt effect",
		"settings.noSensor": "No sensor",
		"settings.language": "Language",
		"settings.languageName": "English",
		"settings.back": "Back",
		"settings.credits": "Music: «Mesmerizing Galaxy» and «Dreamy Flashback» by Kevin MacLeod (incompetech.com), CC BY 4.0\nSounds and particles: Kenney.nl, CC0",
		"settings.on": "On",
		"settings.off": "Off",
		"settings.level.0": "Off",
		"settings.level.1": "Low",
		"settings.level.2": "Medium",
		"settings.level.3": "High",
		"event.survive": "SURVIVE",
		"event.surviveSub": "KEEP THEM OFF THE LINE",
		"event.formation": "FORMATION",
		"event.formationSub": "DOWN THE CROWNED LEADER",
		"event.rush": "RUSH",
		"event.rushSub": "DIVERS FROM THE RAIL",
		"event.boss": "THE SPINNER",
		"event.bossSub": "SHOOT THROUGH THE GAP",
		"popup.pierce": "PIERCE",
		"popup.combo": "COMBO ×%d",
		"popup.split": "SPLIT",
		"popup.blocked": "SHIELD",
		"popup.streak": "STREAK %d",
		"popup.triple": "TRIPLE SHOT",
		"popup.lifeLost": "KNOT SNAPPED",
		"popup.chain": "CHAIN ×%d",
		"skill.bank": "BANK SHOT",
		"skill.long": "LONG SHOT",
		"skill.double": "DOUBLE KILL",
		"skill.triple": "TRIPLE KILL",
		"skill.multi": "%d× KILL",
		"skill.cut": "STRING CUT",
		"skill.clutch": "LAST SECOND",
		"skill.chain": "CHAIN REACTION",
		"overload.title": "OVERLOAD",
		"overload.sub": "EVERYTHING PIERCES · DOUBLE POINTS",
		"overload.hint": "FULL TENSION TRIGGERS OVERLOAD",
		"gameOver.gap": "%s POINTS FROM YOUR BEST",
		"gameOver.close": "SO CLOSE",
		"gameOver.overloads": "OVERLOAD",
		"popup.extraKnot": "+1 KNOT",
		"enemy.new": "NEW ENEMY",
		"enemy.0": "WARDEN|Seeks cover behind others when aimed at. Release before it moves.",
		"enemy.1": "HEAVY|Two hits. Enrages and dives after the first.",
		"enemy.2": "SPLITTER|Breaks into two divers.",
		"enemy.3": "PENDULUM|Always swinging. Time the turn.",
		"enemy.4": "DIVER|Trembles, then dives. Shoot while it shakes.",
		"enemy.5": "SENTRY|Its shield faces you. Bank off a wall or cut the string.",
		"enemy.6": "THE SPINNER|Shoot through the gap between the plates.",
		"enemy.7": "REEL|Winches up when aimed at. Be quick, or bank off a wall.",
		"enemy.8": "SHADE|Fades out at times. Shots pass straight through.",
		"enemy.9": "MEDIC|Mends the others, or bubbles them against one shot. Take it out first.",
		"enemy.10": "MIRROR|Throws clean shots straight back. Hit it with a ball that has bounced.",
		"enemy.11": "PEEP|A little copycat: copies the big ones' tricks and catches the charms they toss.",
		"enemy.12": "PACKY|Hands out trick charms from its sack. Take it out before the tricks spread.",
		"nemesis.11": "PEEPSTER",
		"nemesis.12": "PACKY PETE",
		"charm.title": "TRICK CHARMS",
		"charm.sub": "THEY SHARE TRICKS – SHOOT THE BEAD UNDER AN ENEMY TO BREAK IT",
		"charm.1": "BUBBLE: TAKES ONE SHOT",
		"charm.2": "SPRING: LIGHTNING DODGE",
		"charm.3": "GHOST: FADES OUT",
		"charm.4": "BALLOON: FLOATS UP",
		"charm.5": "VINE: SWINGS AWAY",
		"charm.broken": "TRICK BROKEN +%d",
		"charm.pass": "THEY SHARE TRICKS!",
		"charm.swap": "THEY SWAP TRICKS!",
		"charm.copy": "COPYCAT!",
	},
}

var lang: String:
	get:
		return Prefs.lang


func t(key: String) -> String:
	var table: Dictionary = STRINGS.get(lang, STRINGS["en"])
	if table.has(key):
		return table[key]
	push_warning("Missing string: %s/%s" % [lang, key])
	return STRINGS["en"].get(key, key)


## Which letter of the localized title is the gold one (the ball).
func title_accent() -> int:
	return int(t("game.titleAccent"))


## "MUSIKK: MIDDELS" style setting line.
func setting(key: String, value_key: String) -> String:
	return "%s: %s" % [t(key), t(value_key)]


func on_off(v: bool) -> String:
	return "settings.on" if v else "settings.off"


func set_language(code: String) -> void:
	if code != lang and LANGS.has(code):
		Prefs.set_lang(code)
		language_changed.emit()


func next_language() -> void:
	var i := LANGS.find(lang)
	Prefs.set_lang(LANGS[(i + 1) % LANGS.size()])
	language_changed.emit()
