extends Node
## Localization (autoload `Loc`). Every visible string lives here under a
## dotted key; UI never hardcodes text. Switching language emits
## `language_changed`, and every screen re-reads its strings live.

signal language_changed

const LANGS := ["no", "en"]

const STRINGS := {
	"no": {
		"game.title": "SPENN",
		"game.titleAccent": "2",
		"game.tagline": "HOLD SNORENE UNNA LINJEN",
		"menu.play": "DRA FOR Å SPILLE",
		"menu.best": "REKORD",
		"menu.settings": "INNSTILLINGER",
		"menu.skip": "TRYKK FOR Å HOPPE OVER",
		"menu.stats": "STATISTIKK",
		"menu.skins": "KULER",
		"menu.daily": "DAGENS UTFORDRING",
		"menu.dailyBest": "DAGENS REKORD",
		"menu.missions": "OPPDRAG",
		"mission.done": "OPPDRAG FULLFØRT",
		"mission.kills": "KNUS %s FIENDER I ÉN RUNDE",
		"mission.score": "FÅ %s POENG I ÉN RUNDE",
		"mission.wave": "NÅ BØLGE %s",
		"mission.bank": "LAG %s VEGGSKUDD I ÉN RUNDE",
		"mission.overload": "UTLØS %s OVERBELASTNINGER I ÉN RUNDE",
		"mission.chain": "LAG %s KJEDEREAKSJONER I ÉN RUNDE",
		"mission.cut": "KAPP %s SNORER I ÉN RUNDE",
		"mission.double": "LAG %s DOBBELTTREFF I ÉN RUNDE",
		"mission.survive": "OVERLEV %s SEKUNDER",
		"mission.break": "BRYT %s FORMASJONER I ÉN RUNDE",
		"mission.break.one": "BRYT EN FORMASJON",
		"mission.cut.one": "KAPP EN SNOR",
		"mission.chain.one": "LAG EN KJEDEREAKSJON",
		"stats.title": "STATISTIKK",
		"stats.runs": "RUNDER",
		"stats.best": "REKORD",
		"stats.total": "TOTALE POENG",
		"stats.wave": "BESTE BØLGE",
		"stats.kills": "FIENDER KNUST",
		"stats.accuracy": "TREFFSIKKERHET",
		"stats.missions": "OPPDRAG FULLFØRT",
		"stats.time": "SPILLETID (T:MIN)",
		"skins.title": "KULER",
		"skins.total": "TOTALT %s POENG",
		"skins.equipped": "I BRUK",
		"skins.locked": "LÅSES OPP VED %s",
		"skin.gold": "GULL",
		"skin.copper": "KOBBER",
		"skin.chrome": "KROM",
		"skin.jade": "JADE",
		"skin.obsidian": "OBSIDIAN",
		"skin.ember": "GLØD",
		"hud.wave": "BØLGE %d",
		"wave.clear": "BØLGE %d RENSKET",
		"habit.left": "DE HAR MERKET AT DU SIKTER TIL VENSTRE",
		"habit.right": "DE HAR MERKET AT DU SIKTER TIL HØYRE",
		"habit.rhythm": "DE HAR LÆRT RYTMEN DIN",
		"tactic.1": "UNNVIKELSE",
		"tactic.1.sub": "DE HAR LÆRT Å SE SKUDDET KOMME",
		"tactic.2": "FINTER",
		"tactic.2.sub": "FØLG ØYNENE – DE RØPER RETNINGEN",
		"tactic.3": "RYTMEN DIN",
		"tactic.3.sub": "DE LESER TEMPOET DITT – VARIER DET",
		"tactic.4": "SAMARBEID",
		"tactic.4.sub": "DE SPRER SEG OG STUPER SAMMEN",
		"team.plunge": "SAMLET STUP!",
		"flow.title": "FLYT",
		"flow.badge": "FLYT · RASK LADING · +1×",
		"flow.sub": "RASK LADING · +1 MULTIPLIKATOR",
		"boss.stage": "SPINNEREN · TRINN %d",
		"popup.bubble": "BOBLE",
		"popup.mirror": "SPEIL",
		"skill.break": "FORMASJON BRUTT",
		"pause.title": "PAUSE",
		"pause.resume": "FORTSETT",
		"pause.restart": "START PÅ NYTT",
		"pause.settings": "INNSTILLINGER",
		"pause.mainMenu": "HOVEDMENY",
		"pause.best": "REKORD  %s",
		"pause.hint": "DOBBELTTRYKK FOR PAUSE",
		"gameOver.title": "SPILLET ER OVER",
		"gameOver.score": "POENG",
		"gameOver.bestScore": "BESTE RESULTAT",
		"gameOver.time": "TID",
		"gameOver.accuracy": "TREFF",
		"gameOver.restart": "PRØV IGJEN",
		"gameOver.mainMenu": "HOVEDMENY",
		"record.new": "NY REKORD",
		"settings.title": "INNSTILLINGER",
		"settings.music": "MUSIKK",
		"settings.effects": "EFFEKTER",
		"settings.haptics": "VIBRASJON",
		"settings.reducedMotion": "REDUSERTE ANIMASJONER",
		"settings.aimGuide": "SIKTELINJE",
		"settings.tilt": "VIPPEEFFEKT",
		"settings.noSensor": "INGEN SENSOR",
		"settings.language": "SPRÅK",
		"settings.languageName": "NORSK",
		"settings.back": "TILBAKE",
		"settings.credits": "MUSIKK: «MESMERIZING GALAXY» OG «DREAMY FLASHBACK» AV KEVIN MACLEOD (INCOMPETECH.COM), CC BY 4.0\nLYD OG PARTIKLER: KENNEY.NL, CC0",
		"settings.on": "PÅ",
		"settings.off": "AV",
		"settings.level.0": "AV",
		"settings.level.1": "LAV",
		"settings.level.2": "MIDDELS",
		"settings.level.3": "HØY",
		"event.survive": "OVERLEV",
		"event.surviveSub": "HOLD DEM UNNA LINJEN",
		"event.formation": "FORMASJON",
		"event.formationSub": "FELL LEDEREN MED KRONEN",
		"event.rush": "STORM",
		"event.rushSub": "DYKKERE FRA BJELKEN",
		"event.boss": "SPINNEREN",
		"event.bossSub": "SKYT I SKJOLDGLIPEN",
		"popup.pierce": "GJENNOMSLAG",
		"popup.combo": "KOMBO ×%d",
		"popup.split": "SPLITT",
		"popup.blocked": "SKJOLD",
		"popup.streak": "SERIE %d",
		"popup.triple": "TREDELT SKUDD",
		"popup.lifeLost": "KNUTE RØK",
		"popup.chain": "KJEDE ×%d",
		"skill.bank": "VEGGSKUDD",
		"skill.long": "LANGSKUDD",
		"skill.double": "DOBBELTREFF",
		"skill.triple": "TRIPPELTREFF",
		"skill.multi": "%d-TREFF",
		"skill.cut": "SNORKUTT",
		"skill.clutch": "SISTE SEKUND",
		"skill.chain": "KJEDEREAKSJON",
		"overload.title": "OVERBELASTNING",
		"overload.sub": "ALT GÅR GJENNOM · DOBBEL POENG",
		"overload.hint": "FULL SPENNING GIR OVERBELASTNING",
		"gameOver.gap": "%s POENG FRA REKORDEN",
		"gameOver.close": "SÅ NÆRE",
		"gameOver.overloads": "OVERBELASTNING",
		"popup.extraKnot": "+1 KNUTE",
		"enemy.new": "NY FIENDE",
		"enemy.0": "VAKT|Søker dekning bak andre når du sikter. Slipp før den flytter seg.",
		"enemy.1": "TUNGVEKT|To treff. Blir rasende og stuper etter det første.",
		"enemy.2": "SPLITTER|Deler seg i to dykkere.",
		"enemy.3": "PENDEL|Svinger alltid. Tim vendepunktet.",
		"enemy.4": "DYKKER|Skjelver, så stuper den. Skyt mens den skjelver.",
		"enemy.5": "VOKTER|Skjoldet vender mot deg. Bank via veggen eller kapp snoren.",
		"enemy.6": "SPINNEREN|Skyt i glipen mellom skjoldene.",
		"enemy.7": "SNELLE|Vinsjer seg opp når du sikter. Vær rask, eller bank via veggen.",
		"enemy.8": "SKYGGE|Blir usynlig i perioder. Skudd går gjennom den da.",
		"enemy.9": "LEGEN|Lapper de andre, eller gir dem en boble som tar ett skudd. Ta den først.",
		"enemy.10": "SPEILET|Kaster rene skudd rett tilbake. Treff med en kule som har sprettet.",
	},
	"en": {
		"game.title": "TAUT",
		"game.titleAccent": "1",
		"game.tagline": "KEEP THE STRINGS OFF THE LINE",
		"menu.play": "PULL TO PLAY",
		"menu.best": "BEST",
		"menu.settings": "SETTINGS",
		"menu.skip": "TAP TO SKIP",
		"menu.stats": "STATS",
		"menu.skins": "BALLS",
		"menu.daily": "DAILY CHALLENGE",
		"menu.dailyBest": "TODAY'S BEST",
		"menu.missions": "MISSIONS",
		"mission.done": "MISSION COMPLETE",
		"mission.kills": "BREAK %s ENEMIES IN ONE RUN",
		"mission.score": "SCORE %s IN ONE RUN",
		"mission.wave": "REACH WAVE %s",
		"mission.bank": "MAKE %s BANK SHOTS IN ONE RUN",
		"mission.overload": "TRIGGER %s OVERLOADS IN ONE RUN",
		"mission.chain": "SET OFF %s CHAIN REACTIONS IN ONE RUN",
		"mission.cut": "CUT %s STRINGS IN ONE RUN",
		"mission.double": "MAKE %s DOUBLE KILLS IN ONE RUN",
		"mission.survive": "SURVIVE %s SECONDS",
		"mission.break": "BREAK %s FORMATIONS IN ONE RUN",
		"mission.break.one": "BREAK A FORMATION",
		"mission.cut.one": "CUT A STRING",
		"mission.chain.one": "SET OFF A CHAIN REACTION",
		"stats.title": "STATS",
		"stats.runs": "RUNS",
		"stats.best": "BEST",
		"stats.total": "TOTAL POINTS",
		"stats.wave": "BEST WAVE",
		"stats.kills": "ENEMIES BROKEN",
		"stats.accuracy": "ACCURACY",
		"stats.missions": "MISSIONS DONE",
		"stats.time": "PLAY TIME (H:MIN)",
		"skins.title": "BALLS",
		"skins.total": "%s POINTS IN TOTAL",
		"skins.equipped": "EQUIPPED",
		"skins.locked": "UNLOCKS AT %s",
		"skin.gold": "GOLD",
		"skin.copper": "COPPER",
		"skin.chrome": "CHROME",
		"skin.jade": "JADE",
		"skin.obsidian": "OBSIDIAN",
		"skin.ember": "EMBER",
		"hud.wave": "WAVE %d",
		"wave.clear": "WAVE %d CLEARED",
		"habit.left": "THEY'VE NOTICED YOU FAVOUR THE LEFT",
		"habit.right": "THEY'VE NOTICED YOU FAVOUR THE RIGHT",
		"habit.rhythm": "THEY'VE LEARNED YOUR RHYTHM",
		"tactic.1": "DODGING",
		"tactic.1.sub": "THEY'VE LEARNED TO SEE YOUR SHOT COMING",
		"tactic.2": "FEINTS",
		"tactic.2.sub": "WATCH THE EYES – THEY GIVE IT AWAY",
		"tactic.3": "YOUR RHYTHM",
		"tactic.3.sub": "THEY READ YOUR TIMING – MIX IT UP",
		"tactic.4": "TEAMWORK",
		"tactic.4.sub": "THEY SCATTER AND PLUNGE TOGETHER",
		"team.plunge": "ALL TOGETHER!",
		"flow.title": "FLOW",
		"flow.badge": "FLOW · FAST RELOAD · +1×",
		"flow.sub": "FAST RELOAD · +1 MULTIPLIER",
		"boss.stage": "THE SPINNER · STAGE %d",
		"popup.bubble": "BUBBLE",
		"popup.mirror": "MIRROR",
		"skill.break": "FORMATION BROKEN",
		"pause.title": "PAUSED",
		"pause.resume": "RESUME",
		"pause.restart": "RESTART",
		"pause.settings": "SETTINGS",
		"pause.mainMenu": "MAIN MENU",
		"pause.best": "BEST  %s",
		"pause.hint": "DOUBLE-TAP TO PAUSE",
		"gameOver.title": "GAME OVER",
		"gameOver.score": "SCORE",
		"gameOver.bestScore": "BEST SCORE",
		"gameOver.time": "TIME",
		"gameOver.accuracy": "ACCURACY",
		"gameOver.restart": "TRY AGAIN",
		"gameOver.mainMenu": "MAIN MENU",
		"record.new": "NEW RECORD",
		"settings.title": "SETTINGS",
		"settings.music": "MUSIC",
		"settings.effects": "EFFECTS",
		"settings.haptics": "VIBRATION",
		"settings.reducedMotion": "REDUCED MOTION",
		"settings.aimGuide": "AIM GUIDE",
		"settings.tilt": "TILT EFFECT",
		"settings.noSensor": "NO SENSOR",
		"settings.language": "LANGUAGE",
		"settings.languageName": "ENGLISH",
		"settings.back": "BACK",
		"settings.credits": "MUSIC: «MESMERIZING GALAXY» AND «DREAMY FLASHBACK» BY KEVIN MACLEOD (INCOMPETECH.COM), CC BY 4.0\nSOUNDS AND PARTICLES: KENNEY.NL, CC0",
		"settings.on": "ON",
		"settings.off": "OFF",
		"settings.level.0": "OFF",
		"settings.level.1": "LOW",
		"settings.level.2": "MEDIUM",
		"settings.level.3": "HIGH",
		"event.survive": "SURVIVE",
		"event.surviveSub": "KEEP THEM OFF THE LINE",
		"event.formation": "FORMATION",
		"event.formationSub": "DOWN THE CROWNED LEADER",
		"event.rush": "RUSH",
		"event.rushSub": "DIVERS FROM THE RAIL",
		"event.boss": "THE SPINNER",
		"event.bossSub": "SHOOT THROUGH THE GAP",
		"popup.pierce": "PIERCE",
		"popup.combo": "COMBO ×%d",
		"popup.split": "SPLIT",
		"popup.blocked": "SHIELD",
		"popup.streak": "STREAK %d",
		"popup.triple": "TRIPLE SHOT",
		"popup.lifeLost": "KNOT SNAPPED",
		"popup.chain": "CHAIN ×%d",
		"skill.bank": "BANK SHOT",
		"skill.long": "LONG SHOT",
		"skill.double": "DOUBLE KILL",
		"skill.triple": "TRIPLE KILL",
		"skill.multi": "%d× KILL",
		"skill.cut": "STRING CUT",
		"skill.clutch": "LAST SECOND",
		"skill.chain": "CHAIN REACTION",
		"overload.title": "OVERLOAD",
		"overload.sub": "EVERYTHING PIERCES · DOUBLE POINTS",
		"overload.hint": "FULL TENSION TRIGGERS OVERLOAD",
		"gameOver.gap": "%s POINTS FROM YOUR BEST",
		"gameOver.close": "SO CLOSE",
		"gameOver.overloads": "OVERLOAD",
		"popup.extraKnot": "+1 KNOT",
		"enemy.new": "NEW ENEMY",
		"enemy.0": "WARDEN|Seeks cover behind others when aimed at. Release before it moves.",
		"enemy.1": "HEAVY|Two hits. Enrages and dives after the first.",
		"enemy.2": "SPLITTER|Breaks into two divers.",
		"enemy.3": "PENDULUM|Always swinging. Time the turn.",
		"enemy.4": "DIVER|Trembles, then dives. Shoot while it shakes.",
		"enemy.5": "SENTRY|Its shield faces you. Bank off a wall or cut the string.",
		"enemy.6": "THE SPINNER|Shoot through the gap between the plates.",
		"enemy.7": "REEL|Winches up when aimed at. Be quick, or bank off a wall.",
		"enemy.8": "SHADE|Fades out at times. Shots pass straight through.",
		"enemy.9": "MEDIC|Mends the others, or bubbles them against one shot. Take it out first.",
		"enemy.10": "MIRROR|Throws clean shots straight back. Hit it with a ball that has bounced.",
	},
}

var lang: String:
	get:
		return Prefs.lang


func t(key: String) -> String:
	var table: Dictionary = STRINGS.get(lang, STRINGS["en"])
	if table.has(key):
		return table[key]
	push_warning("Missing string: %s/%s" % [lang, key])
	return STRINGS["en"].get(key, key)


## Which letter of the localized title is the gold one (the ball).
func title_accent() -> int:
	return int(t("game.titleAccent"))


## "MUSIKK: MIDDELS" style setting line.
func setting(key: String, value_key: String) -> String:
	return "%s: %s" % [t(key), t(value_key)]


func on_off(v: bool) -> String:
	return "settings.on" if v else "settings.off"


func next_language() -> void:
	var i := LANGS.find(lang)
	Prefs.set_lang(LANGS[(i + 1) % LANGS.size()])
	language_changed.emit()
